version: "3.7"
services:
  api:
    image: chck/container-tutorial:2.1
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}:/app
    depends_on:
      - myredis
  myredis:
    image: redis:6.0-rc
