version: "3.9"
services:
  api:
    image: chck/with-redis:1.0
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=true
    volumes:
      - ${PWD}:/app
    depends_on:
      - myredis
  myredis:
    image: redis:6.2
